import SectionHeading from '@/components/base/SectionHeading';
import SiteLink from '@/components/base/SiteLink';
import CoachingSupport from '@/components/feature/CoachingSupport';
import Footer from '@/components/feature/Footer';
import MeetMentors from '@/components/feature/MeetMentors';
import PageSectionNav from '@/components/feature/PageSectionNav';
import ProgrammeAccessSections from '@/components/feature/ProgrammeAccessSections';
import SchemaOrg,{ breadcrumbListSchema,courseSchema,organizationSchema } from '@/components/feature/SchemaOrg';
import { evidenceQualityNote,learningSteps,type PathwayConfig } from './pathwayData';

const parentPath = '/project-controls-professional-level-6';
const heroBackgrounds = {
  operational: 'https://images.pexels.com/photos/5833304/pexels-photo-5833304.jpeg?auto=compress&cs=tinysrgb&w=1920',
  strategic: 'https://images.pexels.com/photos/6285078/pexels-photo-6285078.jpeg?auto=compress&cs=tinysrgb&w=1920',
  chartered: 'https://images.pexels.com/photos/19357343/pexels-photo-19357343/free-photo-of-pen-on-documents.jpeg?auto=compress&cs=tinysrgb&w=1920',
} satisfies Record<PathwayConfig['kind'], string>;

function TickList({ items, light = false }: { items: string[]; light?: boolean }) {
  return <ul className="space-y-2">{items.map(item => <li key={item} className={`flex gap-2 text-sm ${light ? 'text-white/75' : 'text-foreground-700'}`}><i className={`ri-check-line mt-0.5 shrink-0 ${light ? 'text-signal-300' : 'text-accent-700'}`} aria-hidden="true" />{item}</li>)}</ul>;
}

function HeroVisual({ kind }: Pick<PathwayConfig, 'kind'>) {
  if (kind === 'strategic') return <div className="relative mx-auto max-w-xl" role="img" aria-label="Projects connecting to programme, portfolio and PMO decision layers"><div className="rounded-2xl border border-white/15 bg-white/[.07] p-5 shadow-2xl">
    <div className="mb-4 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.16em] text-signal-300">Decision architecture</p><span className="text-xs text-white/50">Executive view</span></div>
    {[['PMO governance', 'Standards · assurance · value', 'bg-signal-400/20 border-signal-300/30'], ['Portfolio decisions', 'Priorities · capacity · investment', 'bg-accent-300/15 border-accent-200/25'], ['Programme outcomes', 'Dependencies · benefits · risk', 'bg-primary-300/15 border-primary-200/25']].map(([title, copy, colour], i) => <div key={title} className={`mx-auto mb-3 rounded-xl border p-4 ${colour}`} style={{ width: `${100 - i * 10}%` }}><p className="text-sm font-bold text-white">{title}</p><p className="mt-1 text-xs text-white/60">{copy}</p></div>)}
    <div className="grid grid-cols-3 gap-2">{['Project A', 'Project B', 'Project C'].map((project, i) => <div key={project} className="rounded-lg border border-white/10 bg-white/10 p-3 text-center"><p className="text-xs font-semibold text-white">{project}</p><div className="mx-auto mt-2 h-1.5 rounded bg-white/10"><div className="h-full rounded bg-signal-400" style={{ width: `${55 + i * 14}%` }} /></div></div>)}</div>
  </div></div>;

  if (kind === 'chartered') return <div className="relative mx-auto max-w-xl" role="img" aria-label="Professional evidence and technical knowledge framework supporting chartered progression"><div className="rounded-2xl border border-white/15 bg-white/[.07] p-5 shadow-2xl">
    <div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-signal-300">Professional evidence record</p><p className="mt-1 text-sm text-white">Technical knowledge and practice</p></div><i className="ri-shield-check-line text-2xl text-accent-200" aria-hidden="true" /></div>
    <div className="mt-4 grid grid-cols-2 gap-3">{[['Technical knowledge', 'Recognised route'], ['Professional practice', 'Independent evidence'], ['CPD and ethics', 'APM requirement'], ['Professional judgement', 'Workplace application']].map(([title, label]) => <div key={title} className="rounded-xl border border-white/10 bg-white/10 p-4"><span className="text-xs font-bold uppercase tracking-wider text-signal-300">{label}</span><p className="mt-2 text-sm font-semibold text-white">{title}</p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-1.5 w-3/4 rounded-full bg-accent-300" /></div></div>)}</div>
    <div className="mt-4 rounded-xl border border-signal-300/25 bg-signal-300/10 p-4"><p className="text-xs font-semibold text-white">Clear accountability</p><p className="mt-2 text-xs leading-relaxed text-white/65">KBC develops and assesses the recognised learning component. APM independently controls eligibility, professional assessment and the ChPP award.</p></div>
  </div></div>;

  return <div className="relative mx-auto max-w-xl" role="img" aria-label="Integrated project controls dashboard with schedule, earned value, risk and forecast"><div className="rounded-2xl border border-white/15 bg-white/[.07] p-5 shadow-2xl">
    <div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-signal-300">Illustrative controls view</p><p className="mt-1 text-sm text-white">Sample data, not programme results</p></div><span className="rounded-full bg-accent-300/15 px-3 py-1 text-xs font-bold text-accent-200">EXAMPLE</span></div>
    <div className="mt-4 grid grid-cols-3 gap-2">{[['0.94', 'Schedule index'], ['1.02', 'Cost index'], ['+18d', 'Forecast']].map(([value, label]) => <div key={label} className="rounded-lg bg-white/10 p-3"><p className="text-xl font-bold text-white">{value}</p><p className="text-xs text-white/55">{label}</p></div>)}</div>
    <div className="mt-3 rounded-xl bg-white/10 p-4"><p className="text-xs font-semibold text-white">Integrated schedule</p>{[['Engineering', 84], ['Procurement', 62], ['Delivery', 43]].map(([label, width]) => <div key={String(label)} className="mt-3 grid grid-cols-[76px_1fr] items-center gap-2"><span className="text-xs text-white/60">{label}</span><div className="h-2 rounded bg-white/10"><div className="h-full rounded bg-signal-400" style={{ width: `${width}%` }} /></div></div>)}</div>
    <div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-white">Risk exposure</p><p className="mt-2 text-2xl font-bold text-white">Medium</p><p className="text-xs text-white/50">2 risks trending upward</p></div><div className="rounded-xl bg-signal-300/10 p-4"><p className="text-xs text-white">Required action</p><p className="mt-2 text-xs leading-relaxed text-white/65">Review procurement constraint and recovery options before gate approval.</p></div></div>
  </div></div>;
}

function Process({ config }: { config: PathwayConfig }) {
  return <section id="overview" className="py-16 md:py-24"><div className="container-site"><SectionHeading tag={config.processEyebrow} title={config.processTitle} className="mb-12" /><ol className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{config.process.map(([title, copy], i) => <li key={title} className="relative rounded-xl border border-background-200 bg-white p-5"><span className="text-xs font-bold text-accent-700">0{i + 1}</span><h3 className="mt-3 text-base">{title}</h3><p className="mt-2 text-xs leading-relaxed text-foreground-600">{copy}</p>{i < config.process.length - 1 && <i className="ri-arrow-right-line absolute -right-3 top-1/2 z-10 hidden text-signal-500 lg:block" aria-hidden="true" />}</li>)}</ol></div></section>;
}

function Credits({ config }: { config: PathwayConfig }) {
  return <><section id="pathway" className="bg-primary-700 py-16 text-white md:py-24"><div className="container-site"><SectionHeading tag="Your development journey" title={config.journeyTitle} subtitle={config.journeyIntro} light className="mb-12" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{config.credits.map(credit => <article key={`${credit.number}-${credit.title}`} className="rounded-xl border border-white/15 bg-white/10 p-6"><div className="flex items-center justify-between gap-4"><span className="text-xs font-bold uppercase tracking-wider text-signal-300">Credit {credit.number}</span><span className="text-xs text-white/55">{credit.duration}</span></div><h3 className="mt-4 text-xl text-white">{credit.title}</h3><p className="mt-2 text-xs font-semibold text-accent-200">{credit.owner}</p><p className="mt-4 text-sm text-white/70">{credit.capability}</p><p className="mt-5 border-t border-white/10 pt-4 text-xs text-white/60"><strong className="text-white">Indicative output:</strong> {credit.output}</p></article>)}</div><p className="mt-7 rounded-lg border border-signal-300/25 bg-signal-300/10 p-4 text-xs leading-relaxed text-white/75">{config.creditNote}</p></div></section>
    <section id="credits" className="bg-white py-16 md:py-24"><div className="container-site"><SectionHeading tag="Credit detail" title="Understand the professional context of each credit" subtitle="Open a credit for its capability, workplace application and external-award position." className="mb-10" /><div className="mx-auto max-w-5xl space-y-3">{config.credits.map(credit => <details key={credit.title} className="group rounded-xl border border-background-200 bg-background-50"><summary className="flex cursor-pointer list-none items-center gap-4 p-5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary-600"><span className="flex h-10 min-w-10 items-center justify-center rounded-lg bg-primary-100 px-2 text-xs font-bold text-primary-800">{credit.number}</span><div className="flex-1"><h3 className="text-base">{credit.title}</h3><p className="mt-1 text-xs text-foreground-600">{credit.owner} · {credit.duration}</p></div><i className="ri-add-line text-xl text-primary-700 transition-transform group-open:rotate-45" aria-hidden="true" /></summary><div className="grid gap-5 border-t border-background-200 p-5 md:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-wider text-accent-700">Capability</p><p className="mt-2 text-sm text-foreground-600">{credit.capability}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-accent-700">Workplace output</p><p className="mt-2 text-sm text-foreground-600">{credit.output}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-accent-700">Award position</p><p className="mt-2 text-sm text-foreground-600">{credit.note}</p></div></div></details>)}</div></div></section></>;
}

export default function PathwayPage({ config }: { config: PathwayConfig }) {
  const nav = [{ label: 'Overview', href: '#overview' }, { label: 'Who It Is For', href: '#audience' }, { label: 'Funding & Eligibility', href: '#funding' }, { label: 'Pathway', href: '#pathway' }, { label: 'Capabilities', href: '#capabilities' }, { label: 'Outputs', href: '#outputs' }, { label: 'Experts', href: '#experts' }];
  return <>
    <SchemaOrg type="Organization" data={organizationSchema()} />
    <SchemaOrg type="Course" data={courseSchema({ name: `${config.name} — Project Controls Professional Level 6`, description: config.seoDescription, provider: 'Kent Business College', educationalLevel: 'Level 6', occupationalCategory: 'Project Controls Professional', timeToComplete: 'P27M' })} />
    <SchemaOrg type="WebPage" data={breadcrumbListSchema([{ name: 'Home', item: '/' }, { name: 'Project Controls Professional Level 6', item: parentPath }, { name: config.name }])} />
    <div className="min-h-screen bg-background-50"><main>
      <section id="hero" className="relative flex min-h-[90vh] items-center overflow-hidden bg-primary-950 pb-16 pt-28 text-white md:pb-24 md:pt-36"><img src={heroBackgrounds[config.kind]} alt="" aria-hidden="true" loading="eager" fetchPriority="high" className="absolute inset-0 h-full w-full object-cover object-center opacity-40" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = '/assets/images/hero-professional.webp'; }} /><div className="absolute inset-0 bg-gradient-to-r from-primary-950 via-primary-950/90 to-primary-950/55" aria-hidden="true" /><div className="absolute inset-0 opacity-15" aria-hidden="true" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,.06) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.06) 1px, transparent 1px)', backgroundSize: '44px 44px' }} /><div className="container-site relative grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-16"><div><p className="inline-flex rounded-full border border-signal-300/40 bg-signal-300/10 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-signal-300">{config.eyebrow}</p><h1 className="mt-6 text-display font-bold text-white">{config.name}</h1><p className="mt-6 max-w-2xl text-xl font-semibold leading-snug text-white md:text-2xl">{config.headline}</p><p className="mt-4 max-w-2xl text-sm leading-relaxed text-white/70 md:text-base">{config.intro}</p><p className="mt-6 border-l-2 border-signal-400 pl-4 text-sm font-semibold text-accent-200">{config.value}</p>{config.trust && <p className="mt-4 flex gap-2 rounded-lg border border-white/10 bg-white/[.06] p-4 text-xs leading-relaxed text-white/70"><i className="ri-shield-check-line shrink-0 text-lg text-signal-300" aria-hidden="true" />{config.trust}</p>}<div className="mt-8 flex flex-col gap-3 sm:flex-row"><SiteLink href="/book-a-session" className="btn-primary inline-flex min-h-12 items-center justify-center px-6 text-sm font-bold">{config.kind === 'chartered' ? 'Request a consultation' : 'Request a consultation'} <i className="ri-arrow-right-line ml-2" aria-hidden="true" /></SiteLink><SiteLink href="#pathway" className="cta-button inline-flex min-h-12 items-center justify-center rounded-md border border-white/35 px-6 text-sm font-semibold text-white hover:bg-white/10">Explore the {config.kind === 'strategic' ? 'Six Credits' : 'Pathway'}</SiteLink></div><SiteLink href={`${parentPath}#pathways`} className="mt-5 inline-flex text-sm font-semibold text-white/65 underline decoration-white/30 underline-offset-4 hover:text-white">Compare All Pathways</SiteLink></div><HeroVisual kind={config.kind} /></div></section>
      <section aria-label="Programme facts" className="border-b border-background-200 bg-white py-6"><div className="container-site grid grid-cols-2 gap-5 md:grid-cols-3 lg:grid-cols-6">{[['Level 6', 'Professional level'], ['6 Credits', 'Structured pathway'], ['27 Months', 'Parent programme'], ['Work Based', 'Applied evidence'], ['Live Online', 'Expert-led learning'], ['Professional Development', 'External awards separate']].map(([value, label]) => <div key={value} className="border-l-2 border-signal-400 pl-3"><p className="text-sm font-bold text-primary-800">{value}</p><p className="mt-1 text-xs text-foreground-600">{label}</p></div>)}</div></section>
      <PageSectionNav pageLabel={config.name.replace(' Pathway', '')} links={nav} ctaHref="/book-a-session" ctaLabel="Request a consultation" />
      <section id="audience" className="bg-white py-16 md:py-24"><div className="container-site"><SectionHeading tag="Who should choose this pathway?" title={config.rolesTitle} className="mb-12" /><div className="grid gap-5 lg:grid-cols-3">{config.roleGroups.map(group => <article key={group.title} className="card-premium p-6"><h3 className="text-xl">{group.title}</h3><div className="mt-5"><TickList items={group.roles} /></div></article>)}</div><p className="mt-7 rounded-xl border-l-4 border-signal-500 bg-highlight-50 p-5 text-sm leading-relaxed text-foreground-700">{config.roleNote}</p></div></section>
      <ProgrammeAccessSections programmeName={config.name} />
      <Process config={config} />
      <Credits config={config} />
      <section id="capabilities" className="py-16 md:py-24"><div className="container-site"><SectionHeading tag="What you will develop" title={config.capabilityTitle} className="mb-12" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{config.capabilities.map(([title, copy], i) => <article key={title} className="rounded-xl border border-background-200 bg-white p-6"><span className="text-xs font-bold text-accent-700">{String(i + 1).padStart(2, '0')}</span><h3 className="mt-3 text-lg">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-600">{copy}</p></article>)}</div></div></section>
      <section className="bg-secondary-600 py-16 text-white md:py-24"><div className="container-site grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-signal-300">Connected thinking</p><h2 className="mt-4 text-3xl text-white md:text-4xl">{config.systemTitle}</h2><p className="mt-4 text-sm leading-relaxed text-white/70">{config.systemCopy}</p></div><div><div className="rounded-2xl border border-white/15 bg-white/10 p-6"><p className="text-center text-xs font-bold uppercase tracking-[.16em] text-signal-300">{config.systemCentre}</p><div className="mt-5 flex flex-wrap justify-center gap-2">{config.systemItems.map(item => <span key={item} className="rounded-full border border-white/15 bg-white/10 px-3 py-2 text-xs font-semibold text-white/80">{item}</span>)}</div></div><div className="mt-4 flex flex-wrap items-center justify-center gap-2">{config.systemExample.map((item, i) => <span key={item} className="contents"><span className="rounded bg-white/10 px-3 py-2 text-xs font-semibold text-white/75">{item}</span>{i < config.systemExample.length - 1 && <i className="ri-arrow-right-line text-signal-300" aria-hidden="true" />}</span>)}</div></div></div></section>
      <section id="outputs" className="bg-white py-16 md:py-24"><div className="container-site"><SectionHeading tag="Apply it at work" title={config.outputsTitle} className="mb-12" /><div className="grid gap-5 lg:grid-cols-3">{config.outputGroups.map(group => <article key={group.title} className="rounded-xl bg-background-100 p-6"><h3 className="text-xl">{group.title}</h3><div className="mt-5"><TickList items={group.items} /></div></article>)}</div><p className="mt-7 rounded-xl border-l-4 border-accent-600 bg-background-100 p-5 text-sm leading-relaxed text-foreground-700"><strong className="text-foreground-900">What good evidence looks like: </strong>{evidenceQualityNote}</p></div></section>
      <section className="py-16 md:py-24"><div className="container-site"><SectionHeading tag={config.kind === 'chartered' ? 'From knowledge to evidence' : 'From evidence to action'} title={config.decisionTitle} subtitle={config.decisionCopy} className="mb-12" /><div className="flex flex-wrap items-center justify-center gap-2">{config.decision.map((item, i) => <span key={item} className="contents"><span className="rounded-lg bg-primary-700 px-4 py-3 text-xs font-bold uppercase tracking-wider text-white">{item}</span>{i < config.decision.length - 1 && <i className="ri-arrow-right-line text-signal-500" aria-hidden="true" />}</span>)}</div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{config.decisionPillars.map(([title, copy]) => <article key={title} className="border-t-2 border-accent-600 pt-4"><h3 className="text-lg">{title}</h3><p className="mt-2 text-sm text-foreground-600">{copy}</p></article>)}</div></div></section>
      <section id="learning" className="bg-white py-16 md:py-24"><div className="container-site"><SectionHeading tag="Learning experience" title="Learn, apply, evidence, review, improve" subtitle="Live teaching, guided learning, workplace application, coaching and professional reflection form one continuous cycle." className="mb-12" /><ol className="grid gap-4 md:grid-cols-5">{learningSteps.map(([title, copy], i) => <li key={title} className="rounded-xl border border-background-200 p-5"><span className="text-xs font-bold text-accent-700">0{i + 1}</span><h3 className="mt-3 text-lg">{title}</h3><p className="mt-2 text-xs leading-relaxed text-foreground-600">{copy}</p></li>)}</ol></div></section>
      <div id="experts"><MeetMentors /></div>
      <CoachingSupport />
      <section className="bg-primary-700 py-16 text-white md:py-24"><div className="container-site"><SectionHeading tag="For employers" title={config.employerTitle} light className="mb-12" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{config.employerBenefits.map(([title, copy]) => <article key={title} className="rounded-xl border border-white/15 bg-white/10 p-5"><h3 className="text-lg text-white">{title}</h3><p className="mt-2 text-sm text-white/65">{copy}</p></article>)}</div><div className="mt-8 text-center"><SiteLink href="/employers" className="btn-primary inline-flex min-h-12 items-center px-6 text-sm font-bold">Discuss This Pathway for Your Team <i className="ri-arrow-right-line ml-2" aria-hidden="true" /></SiteLink></div></div></section>
      <section className="bg-white py-16 md:py-24"><div className="container-site"><SectionHeading tag="Professional development and recognition" title={config.recognitionTitle} subtitle={config.recognitionCopy} className="mb-12" /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{config.recognitionItems.map(([title, copy]) => <article key={title} className="rounded-xl border border-background-200 p-5"><h3 className="text-base">{title}</h3><p className="mt-3 text-sm leading-relaxed text-foreground-600">{copy}</p></article>)}</div>{config.kind === 'chartered' && <p className="mt-7 rounded-xl border border-highlight-300 bg-highlight-50 p-5 text-sm font-semibold text-foreground-800">Completion of the Kent Business College Chartered Pathway does not itself confer Chartered Project Professional status.</p>}</div></section>
      <section className="py-16 md:py-24"><div className="container-site"><SectionHeading tag="Programme essentials" title="The complete Level 6 journey at a glance" className="mb-12" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[['Delivery', 'Live online teaching, guided study, coaching and workplace application.'], ['Duration and credits', '27 months: one-month soft start, six credits over 24 months and two months of closing workshops.'], ['Evidence and EPA', 'Authentic workplace evidence, portfolio development and End-Point Assessment readiness.'], ['Employer support', 'Suitable duties, evidence access, protected learning time and progress-review participation.'], ['Initial assessment', 'Role fit, prior learning, eligibility, evidence opportunities and support needs.'], ['Off-the-job learning', 'A protected learning plan is confirmed at enrolment against the current occupational standard and funding rules.']].map(([title, copy]) => <article key={title} className="rounded-xl bg-white p-6 shadow-sm"><h3 className="text-lg">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-600">{copy}</p></article>)}</div></div></section>
      <section className="bg-secondary-600 py-16 text-white md:py-20"><div className="container-site text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-signal-300">Take the next step</p><h2 className="mx-auto mt-4 max-w-3xl text-3xl text-white md:text-4xl">{config.finalTitle}</h2><p className="mx-auto mt-4 max-w-2xl text-sm text-white/70">{config.finalCopy}</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><SiteLink href="/book-a-session" className="btn-primary inline-flex min-h-12 items-center justify-center px-6 text-sm font-bold">{config.kind === 'chartered' ? 'Request a consultation' : 'Request a consultation'}</SiteLink><SiteLink href={`${parentPath}#pathways`} className="cta-button inline-flex min-h-12 items-center justify-center rounded-md border border-white/30 px-6 text-sm font-semibold text-white">Compare All Pathways</SiteLink></div></div></section>
    </main><Footer /></div>
  </>;
}
