import { requireSupabaseClient } from '@/lib/supabase';
import { fromSupabase } from './supabaseFallback';

export interface EventCategory { id: number; name: string; slug: string; kind: 'eventbrite' | 'local' | 'programme'; is_visible: boolean; order: number; remote_id: string }
export interface EventItem { id: number; slug: string; title: string; category: string; source: 'manual' | 'eventbrite'; source_category: EventCategory | null; classifications: EventCategory[]; format: 'online' | 'in_person'; cadence: string; display_summary: string; description?: string; image_url: string; image_alt: string; starts_at: string | null; ends_at: string | null; timezone: string; location: string; organizer: string; state: 'upcoming' | 'ended' | 'cancelled'; sales_status: string; price_label: string; is_featured: boolean; highlights_url: string; booking_url: string; booking_label: string; last_synced_at: string | null; availability_stale: boolean; }
export interface EventResults { count: number; results: EventItem[]; next: string | null; previous: string | null }
export class EventRequestError extends Error { status: number; constructor(status: number) { super('Unable to load events'); this.status = status; } }

type EventRow = Record<string, unknown> & { source_category?: Record<string, unknown> | null; event_classifications?: Array<{ event_categories?: Record<string, unknown> | null }> };
function category(row: Record<string, unknown> | null | undefined): EventCategory | null { if (!row) return null; return { id: Number(row.id), name: String(row.name ?? ''), slug: String(row.slug ?? ''), kind: String(row.kind ?? 'local') as EventCategory['kind'], remote_id: String(row.remote_id ?? ''), is_visible: Boolean(row.is_visible), order: Number(row.order ?? 0) }; }
function eventState(row: EventRow): EventItem['state'] { const status = String(row.remote_status ?? ''); if (status === 'canceled' || status === 'cancelled') return 'cancelled'; const comparison = row.ends_at ?? row.starts_at; if (comparison && String(comparison) <= new Date().toISOString()) return 'ended'; return 'upcoming'; }
function availabilityStale(row: EventRow) { if (row.source !== 'eventbrite') return false; if (!row.last_synced_at) return true; return String(row.last_synced_at) < new Date(Date.now() - 30 * 60_000).toISOString(); }
function bookingUrl(row: EventRow) { if (eventState(row) !== 'upcoming') return ''; if ((row.sales_status === 'sold_out' || row.sales_status === 'unavailable') && !availabilityStale(row)) return ''; const url = String(row.source === 'eventbrite' ? row.source_url ?? '' : row.cta_href ?? ''); return (/^https?:\/\//.test(url) || url.startsWith('/')) && !url.startsWith('//') ? url : ''; }
function bookingLabel(row: EventRow) { const state = eventState(row); if (state === 'cancelled') return 'Event cancelled'; if (state === 'ended') return 'Event ended'; if (availabilityStale(row)) return 'Check availability on Eventbrite'; if (row.sales_status === 'sold_out') return 'Sold out'; if (row.sales_status === 'unavailable') return 'Registration unavailable'; return row.source === 'eventbrite' ? 'Register on Eventbrite' : String(row.cta_label ?? 'Register'); }
function fromRow(row: EventRow): EventItem { const classifications = (row.event_classifications ?? []).map((item) => category(item.event_categories)).filter((item): item is EventCategory => Boolean(item)); return { id: Number(row.id), slug: String(row.slug ?? ''), title: String(row.title ?? ''), category: String(row.category ?? ''), source: String(row.source ?? 'manual') as EventItem['source'], source_category: category(row.source_category), classifications, format: String(row.format ?? 'online') as EventItem['format'], cadence: String(row.cadence ?? ''), display_summary: String(row.summary || row.description || '').slice(0, 350), description: String(row.description ?? ''), image_url: String(row.image_url ?? ''), image_alt: String(row.image_alt ?? ''), starts_at: row.starts_at ? String(row.starts_at) : null, ends_at: row.ends_at ? String(row.ends_at) : null, timezone: String(row.timezone ?? 'Europe/London'), location: String(row.location ?? ''), organizer: String(row.organizer ?? ''), state: eventState(row), sales_status: String(row.sales_status ?? ''), price_label: String(row.price_label ?? ''), is_featured: Boolean(row.is_featured), highlights_url: String(row.highlights_url ?? ''), booking_url: bookingUrl(row), booking_label: bookingLabel(row), last_synced_at: row.last_synced_at ? String(row.last_synced_at) : null, availability_stale: availabilityStale(row) }; }
function page(items: EventItem[], requestedPage = 1, pageSize = 12): EventResults { const count = items.length; const start = Math.max(0, requestedPage - 1) * pageSize; return { count, results: items.slice(start, start + pageSize), next: start + pageSize < count ? String(requestedPage + 1) : null, previous: requestedPage > 1 ? String(requestedPage - 1) : null }; }
function applyFilters(items: EventItem[], params: Record<string, string | number | undefined>) { const now = new Date().toISOString(); let next = items; const scope = String(params.scope ?? 'upcoming'); if (scope === 'past') next = next.filter((e) => (e.ends_at ?? e.starts_at ?? '') <= now); else if (scope !== 'all') next = next.filter((e) => !((e.ends_at ?? e.starts_at ?? '') <= now)); if (params.search) { const s = String(params.search).toLowerCase(); next = next.filter((e) => `${e.title} ${e.description ?? ''} ${e.display_summary} ${e.location}`.toLowerCase().includes(s)); } if (params.category) next = next.filter((e) => e.source_category?.slug === params.category); if (params.classification) next = next.filter((e) => e.classifications.some((c) => c.slug === params.classification)); if (params.programme) next = next.filter((e) => e.classifications.some((c) => c.slug === params.programme)); if (params.format) next = next.filter((e) => e.format === params.format); if (params.exclude) next = next.filter((e) => e.slug !== params.exclude); return next; }
async function loadEventsFromSupabase() { const supabase = requireSupabaseClient(); const { data, error } = await supabase.from('events').select('*, source_category:event_categories!events_source_category_id_fkey(*), event_classifications(event_categories(*))').eq('is_active', true).order('is_featured', { ascending: false }).order('order', { ascending: true }).order('starts_at', { ascending: true, nullsFirst: false }).order('id', { ascending: true }); if (error) throw error; return (data ?? []).map((row) => fromRow(row as EventRow)); }

export const fetchEventOptions = (_signal?: AbortSignal) => fromSupabase(async () => { const supabase = requireSupabaseClient(); const { data, error } = await supabase.from('event_categories').select('*').eq('is_visible', true).order('order').order('name'); if (error) throw error; return (data ?? []).map((row) => category(row)).filter((item): item is EventCategory => Boolean(item)); }, 'event options');
export const fetchEvent = (slug: string, _signal?: AbortSignal) => fromSupabase(async () => { const events = await loadEventsFromSupabase(); const event = events.find((item) => item.slug === slug); if (!event) throw new EventRequestError(404); return event; }, 'event detail');
export const fetchEventLibrary = (params: Record<string, string | number | undefined> = {}, _signal?: AbortSignal) => fromSupabase(async () => page(applyFilters(await loadEventsFromSupabase(), params), Number(params.page ?? 1), Number(params.page_size ?? params.pageSize ?? 12)), 'event library');
export function eventDate(event: EventItem, end = false) { const value = end ? event.ends_at : event.starts_at; if (!value) return end ? '' : event.cadence || 'Date to be confirmed'; return new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: event.timezone || 'Europe/London' }).format(new Date(value)); }