import { useEffect, useId, useState } from 'react';
import SiteLink from '@/components/base/SiteLink';
import { fetchReviews, type Review } from '@/services/testimonialsApi';

export default function TestimonialsSection({ programme, title = 'What professionals and employers say', id }: { programme?: string; title?: string; id?: string }) {
  const heading = useId(); const [reviews, setReviews] = useState<Review[]>([]); const [status, setStatus] = useState('loading');
  const [audience, setAudience] = useState<Review['reviewer_type']>('professional'); const [index, setIndex] = useState(0); const [revision, setRevision] = useState(0);
  useEffect(() => {
    const controller = new AbortController(); setStatus('loading');
    fetchReviews(programme, controller.signal).then(data => { if (!controller.signal.aborted) { setReviews(data); setAudience(data.some(r => r.reviewer_type === 'professional') ? 'professional' : 'employer'); setIndex(0); setStatus('ready'); } }).catch(() => { if (!controller.signal.aborted) setStatus('error'); });
    return () => controller.abort();
  }, [programme, revision]);
  const items = reviews.filter(r => r.reviewer_type === audience); const current = items[Math.min(index, items.length - 1)];
  const shareLink = `/contact?review=1${programme ? `&programme=${encodeURIComponent(programme)}` : ''}`;
  return <section id={id} aria-labelledby={heading} className="overflow-hidden bg-background-100 py-16 md:py-20"><div className="container-site">
    <div className="mx-auto max-w-3xl text-center"><p className="inline-flex items-center gap-2 rounded-full border border-signal-400/60 px-4 py-2 text-xs font-bold uppercase tracking-wider text-signal-700"><i className="ri-user-star-line" aria-hidden="true" />Professional experience</p><h2 id={heading} className="mt-5 text-3xl font-bold text-foreground-950 md:text-4xl">{title}</h2><p className="mt-4 text-foreground-600">Experiences shared by our professionals and employers.</p></div>
    {status === 'loading' ? <p role="status" className="py-12 text-center">Loading experiences…</p> : status === 'error' ? <div role="alert" className="py-10 text-center"><p>Reviews could not be loaded.</p><button onClick={() => setRevision(v => v + 1)} className="mt-4 font-semibold text-primary-700 underline">Try again</button></div> : !reviews.length ? <div className="mx-auto mt-9 max-w-2xl rounded-2xl border border-background-200 bg-white p-8 text-center"><h3 className="text-xl font-bold">Share your programme experience</h3><p className="mt-3 text-sm leading-relaxed text-foreground-600">Completed a programme with us? Tell others about your learning and how you have applied it at work.</p></div> : <>
      <div className="mt-8 flex flex-wrap justify-center gap-3" aria-label="Review audience">{(['professional', 'employer'] as const).map(type => <button key={type} aria-pressed={audience === type} onClick={() => { setAudience(type); setIndex(0); }} className={`inline-flex min-h-11 items-center gap-3 rounded-full border px-5 py-2 text-sm font-semibold ${audience === type ? 'border-primary-700 bg-primary-700 text-white' : 'border-background-300 bg-white text-foreground-700'}`}><i className={type === 'professional' ? 'ri-user-star-line' : 'ri-building-line'} aria-hidden="true" />{type === 'professional' ? 'Professionals' : 'Employers'}<span className="rounded-full bg-current/10 px-2 py-0.5">{reviews.filter(r => r.reviewer_type === type).length}</span></button>)}</div>
      {current ? <div className="mx-auto mt-10 max-w-5xl"><div className="mb-5 flex gap-3"><button disabled={index === 0} onClick={() => setIndex(i => i - 1)} aria-label="Previous testimonial" className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-700 text-white disabled:opacity-30"><i className="ri-arrow-left-s-line text-xl" aria-hidden="true" /></button><button disabled={index >= items.length - 1} onClick={() => setIndex(i => i + 1)} aria-label="Next testimonial" className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-700 text-white disabled:opacity-30"><i className="ri-arrow-right-s-line text-xl" aria-hidden="true" /></button></div>
        <div className="grid items-start gap-8 md:grid-cols-[280px_minmax(0,1fr)] lg:gap-12" aria-live="polite"><figure className="mx-auto w-full max-w-xs overflow-hidden rounded-2xl border border-background-200 bg-white shadow-sm"><img src={current.photo_url} alt={current.name} className="aspect-[4/5] w-full object-cover" /><figcaption className="p-5 text-center"><p className="font-bold text-foreground-950">{current.name}</p><p className="mt-2 text-sm text-foreground-600">{current.programme_label}</p><span className="mx-auto mt-4 block h-0.5 w-8 bg-signal-400" /></figcaption></figure><div><blockquote className="rounded-2xl border border-background-200 bg-white p-7 shadow-sm md:p-10"><i className="ri-double-quotes-l text-5xl text-primary-500" aria-hidden="true" /><p className="mt-4 whitespace-pre-line break-words text-lg leading-relaxed text-foreground-700">{current.review}</p></blockquote><p className="mt-5 inline-block rounded-full border border-primary-200 bg-white px-4 py-1 text-sm font-semibold text-primary-700">{index + 1} / {items.length}</p></div></div>
        {items.length > 1 && <div className="mt-8 overflow-x-auto py-2" aria-label="Select testimonial"><div className="mx-auto flex w-max gap-3">{items.map((review, i) => <button key={review.id} onClick={() => setIndex(i)} aria-label={`Read ${review.name}'s review`} aria-pressed={index === i} className={`h-16 w-16 shrink-0 overflow-hidden rounded-xl border-2 p-0.5 ${index === i ? 'border-primary-600' : 'border-transparent opacity-50 hover:opacity-100'}`}><img src={review.photo_url} alt="" loading="lazy" className="h-full w-full rounded-lg object-cover" /></button>)}</div></div>}
      </div> : <p className="mt-10 text-center text-sm text-foreground-600">No {audience === 'professional' ? 'professional' : 'employer'} experiences published yet.</p>}
    </>}
    <div className="mt-9 flex flex-wrap justify-center gap-4"><SiteLink href={shareLink} className="btn-primary inline-flex min-h-12 items-center gap-2 px-6 text-sm font-bold">Share your experience<i className="ri-arrow-right-line" aria-hidden="true" /></SiteLink></div>
  </div></section>;
}
