import SectionHeading from '@/components/base/SectionHeading';
import SiteLink from '@/components/base/SiteLink';

const developmentAreas = [
  { title: 'Project Management Foundations', description: 'Develop professionals who coordinate delivery, stakeholders, governance, planning and project performance.', programmes: ['Associate Project Manager Level 4', 'Workplace-based project management development'], href: '/associate-project-manager-level-4', cta: 'Explore Level 4', icon: 'ri-stack-line' },
  { title: 'Advanced Project Controls', description: 'Build integrated capability across planning, scheduling, cost, risk, change, forecasting and performance reporting.', programmes: ['Project Controls Professional Level 6', 'Strategic and operational route options'], href: '/project-controls-professional-level-6', cta: 'Explore Level 6', icon: 'ri-line-chart-line' },
  { title: 'PMO, Governance & Assurance', description: 'Strengthen portfolio insight, governance, assurance, controls integration and executive decision support.', programmes: ['PMO and Governance route', 'Chartered progression support'], href: '/project-controls-professional/pmo-governance-route', cta: 'Explore PMO Development', icon: 'ri-government-line' },
];

export default function ProjectControlsPathways() {
  return (
<section id="programmes" className="bg-primary-700 py-16 text-white md:py-24"><div className="container-site"><SectionHeading tag="Project controls pathways" title="Build capability where your project environment needs it most." subtitle="Our pathways combine structured professional learning with direct application across project management, project controls, PMO and governance responsibilities." light className="mb-12" /><div className="grid gap-5 lg:grid-cols-3">{developmentAreas.map(a => <article key={a.title} className="flex flex-col rounded-xl border border-white/15 bg-white/10 p-7"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-white/10 text-signal-300"><i className={`${a.icon} text-xl`} /></span><h3 className="mt-5 text-xl text-white">{a.title}</h3><p className="mt-3 text-sm text-white/70">{a.description}</p><ul className="mt-5 flex-1 space-y-2">{a.programmes.map(p => <li key={p} className="flex gap-2 text-sm text-white/85"><i className="ri-check-line text-signal-300" />{p}</li>)}</ul><SiteLink href={a.href} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-signal-300">{a.cta}<i className="ri-arrow-right-line" /></SiteLink></article>)}</div><div className="mt-10 flex flex-col items-start justify-between gap-5 rounded-xl bg-white p-7 text-foreground-900 md:flex-row md:items-center"><div><h3 className="text-xl">Not sure which project controls route fits the role?</h3><p className="mt-2 max-w-2xl text-sm text-foreground-600">Start with the employee's project responsibilities rather than the programme title. Our team can help identify the most suitable level and route.</p></div><SiteLink href="/book-a-session" className="btn-primary inline-flex min-h-12 shrink-0 items-center px-6 text-sm font-bold">Discuss a Role With Us</SiteLink></div></div></section>
  );
}
