-- Generated from backend/db.sqlite3 for Supabase public-content migration.
-- Run after SUPABASE_PUBLIC_CONTENT_SCHEMA.sql.
-- Uses upserts; no deletes or truncates.
begin;

insert into public.ipc_images (id, image_url, alt_text, "order", is_active) values
  (8, 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/baabc2486e8140a0a54d73c0a6b03ddc.webp', '', 0, true),
  (9, 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/89714eed661347a6ab062e7eaa8795d5.webp', '', 0, true),
  (10, 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/8ad91f0e98b8496eae53a3ddacbee926.webp', '', 0, true),
  (11, 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/f3da5d5fa9154ac894198bf592a86041.webp', '', 0, true),
  (12, 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/c1001573b51548e8b716a16318ae9eea.webp', '', 0, true)
on conflict (id) do update set image_url = excluded.image_url, alt_text = excluded.alt_text, "order" = excluded."order", is_active = excluded.is_active;

insert into public.partners (id, name, image_url, link_url, "order", is_active, created_at, updated_at) values
  (28, '', '/assets/media/partners/2026/09/partner-1.webp', '', 10, true, '2026-09-07 09:12:34.239811', '2026-09-07 09:12:34.239853'),
  (29, '', '/assets/media/partners/2026/09/partner-2.png', '', 20, true, '2026-09-07 09:12:34.247685', '2026-09-07 09:12:34.247712'),
  (3, '', '/assets/media/partners/2026/09/partner-3.jpg', '', 30, true, '2026-09-07 08:16:35.299984', '2026-09-07 08:16:35.300004'),
  (4, '', '/assets/media/partners/2026/09/partner-4.jpg', '', 40, true, '2026-09-07 08:16:35.306878', '2026-09-07 08:16:35.306898'),
  (5, '', '/assets/media/partners/2026/09/partner-5.png', '', 50, true, '2026-09-07 08:16:35.313063', '2026-09-07 08:16:35.313088'),
  (6, '', '/assets/media/partners/2026/09/partner-6.png', '', 60, true, '2026-09-07 08:16:35.319521', '2026-09-07 08:16:35.319544'),
  (7, '', '/assets/media/partners/2026/09/partner-7.png', '', 70, true, '2026-09-07 08:16:35.325615', '2026-09-07 08:16:35.325636'),
  (8, '', '/assets/media/partners/2026/09/partner-8.png', '', 80, true, '2026-09-07 08:16:35.332163', '2026-09-07 08:16:35.332184'),
  (9, '', '/assets/media/partners/2026/09/partner-9.webp', '', 90, true, '2026-09-07 08:16:35.337734', '2026-09-07 08:16:35.337755'),
  (10, '', '/assets/media/partners/2026/09/partner-10.jpg', '', 100, true, '2026-09-07 08:16:35.344257', '2026-09-07 08:16:35.344277'),
  (11, '', '/assets/media/partners/2026/09/partner-11.png', '', 110, true, '2026-09-07 08:16:35.350967', '2026-09-07 08:16:35.350988'),
  (12, '', '/assets/media/partners/2026/09/partner-12.png', '', 120, true, '2026-09-07 08:16:35.357423', '2026-09-07 08:16:35.357445'),
  (13, '', '/assets/media/partners/2026/09/partner-13.png', '', 130, true, '2026-09-07 08:16:35.363411', '2026-09-07 08:16:35.363433'),
  (14, '', '/assets/media/partners/2026/09/partner-14.png', '', 140, true, '2026-09-07 08:16:35.369501', '2026-09-07 08:16:35.369520'),
  (15, '', '/assets/media/partners/2026/09/partner-15.png', '', 150, true, '2026-09-07 08:16:35.375166', '2026-09-07 08:16:35.375189'),
  (16, '', '/assets/media/partners/2026/09/partner-16.jpg', '', 160, true, '2026-09-07 08:16:35.380777', '2026-09-07 08:16:35.380797'),
  (17, '', '/assets/media/partners/2026/09/partner-17.png', '', 170, true, '2026-09-07 08:16:35.386669', '2026-09-07 08:16:35.386693'),
  (18, '', '/assets/media/partners/2026/09/partner-18.png', '', 180, true, '2026-09-07 08:16:35.392715', '2026-09-07 08:16:35.392736'),
  (19, '', '/assets/media/partners/2026/09/partner-19.jpg', '', 190, true, '2026-09-07 08:16:35.398690', '2026-09-07 08:16:35.398711'),
  (20, '', '/assets/media/partners/2026/09/partner-20.png', '', 200, true, '2026-09-07 08:16:35.404274', '2026-09-07 08:16:35.404294'),
  (21, '', '/assets/media/partners/2026/09/partner-21.jpg', '', 210, true, '2026-09-07 08:16:35.410289', '2026-09-07 08:16:35.410310'),
  (22, '', '/assets/media/partners/2026/09/partner-22.png', '', 220, true, '2026-09-07 08:16:35.416345', '2026-09-07 08:16:35.416365'),
  (23, '', '/assets/media/partners/2026/09/partner-23.png', '', 230, true, '2026-09-07 08:16:35.422386', '2026-09-07 08:16:35.422407'),
  (24, '', '/assets/media/partners/2026/09/partner-24.webp', '', 240, true, '2026-09-07 08:16:35.428910', '2026-09-07 08:16:35.428932'),
  (25, '', '/assets/media/partners/2026/09/partner-25.webp', '', 250, true, '2026-09-07 08:16:35.435190', '2026-09-07 08:16:35.435211'),
  (26, '', '/assets/media/partners/2026/09/partner-26.png', '', 260, true, '2026-09-07 08:16:35.441551', '2026-09-07 08:16:35.441572')
on conflict (id) do update set name = excluded.name, image_url = excluded.image_url, link_url = excluded.link_url, "order" = excluded."order", is_active = excluded.is_active, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.sectors (id, slug, title, description, icon, image_url, link_url, "order", is_active, created_at, updated_at) values
  (1, 'construction', 'Construction', 'Planning, controls, cost, contracts and risk across complex delivery.', 'ri-building-line', 'https://readdy.ai/api/search-image?query=Abstract%20geometric%20construction%20crane%20and%20steel%20building%20framework%20silhouette%2C%20warm%20burnt%20orange%20and%20concrete%20grey%20tones%2C%20minimalist%20editorial%20illustration%20style%2C%20clean%20lines%2C%20no%20people%2C%20professional%20business%20aesthetic%2C%20soft%20gradient%20background&width=600&height=400&seq=construction-sector-2026&orientation=landscape', '/project-controls-professional/construction-route', 10, true, '2026-09-08 08:42:22.237894', '2026-09-08 08:42:22.237914'),
  (2, 'engineering', 'Engineering', 'Integration, scheduling, cost and controls across engineering environments.', 'ri-settings-4-line', 'https://readdy.ai/api/search-image?query=Abstract%20precision%20aerospace%20engineering%20geometry%2C%20turbine%20blades%20and%20mechanical%20gears%20silhouette%2C%20metallic%20silver%20and%20cool%20steel%20blue%20tones%2C%20minimalist%20editorial%20illustration%2C%20no%20people%2C%20professional%20manufacturing%20aesthetic%2C%20soft%20gradient%20background&width=600&height=400&seq=engineering-sector-2026&orientation=landscape', '/project-controls-professional/engineering-manufacturing-aerospace-route', 20, true, '2026-09-08 08:42:22.244045', '2026-09-08 08:42:22.244065'),
  (3, 'public-sector', 'Public Sector', 'Governance, assurance, capital programmes and accountable delivery.', 'ri-government-line', 'https://readdy.ai/api/search-image?query=Abstract%20classical%20government%20building%20with%20column%20architecture%20and%20modern%20geometric%20overlay%2C%20sage%20green%20and%20warm%20stone%20tones%2C%20minimalist%20editorial%20illustration%2C%20no%20people%2C%20professional%20institutional%20aesthetic%2C%20soft%20gradient%20background&width=600&height=400&seq=public-sector-2026&orientation=landscape', '/project-controls-professional/public-sector-councils-route', 30, true, '2026-09-08 08:42:22.250066', '2026-09-08 08:42:22.250085'),
  (4, 'energy', 'Energy & Utilities', 'Planning, cost, risk and controls across complex assets and programmes.', 'ri-flashlight-line', 'https://readdy.ai/api/search-image?query=Abstract%20offshore%20oil%20platform%20and%20wind%20turbine%20silhouettes%2C%20deep%20teal%20and%20navy%20blue%20tones%2C%20geometric%20minimalist%20style%2C%20clean%20editorial%20illustration%2C%20no%20people%2C%20professional%20energy%20sector%20aesthetic%2C%20soft%20gradient%20background&width=600&height=400&seq=energy-sector-2026&orientation=landscape', '/project-controls-professional/energy-oil-gas-utilities-route', 40, true, '2026-09-08 08:42:22.257215', '2026-09-08 08:42:22.257240')
on conflict (id) do update set slug = excluded.slug, title = excluded.title, description = excluded.description, icon = excluded.icon, image_url = excluded.image_url, link_url = excluded.link_url, "order" = excluded."order", is_active = excluded.is_active, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.professional_credentials (id, name, role, image_url, link_url, "order", is_active, created_at, updated_at) values
  (7, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/cdd75277ca3b4fda854f4f28e08d5a99.png', '', 10, true, '2026-09-27 14:27:14.717099', '2026-09-27 14:27:14.717169'),
  (9, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/f9aa7c48f2c34d6ea1cc63e895046f6f.png', '', 20, true, '2026-09-27 14:27:33.382767', '2026-09-27 14:29:11.889164'),
  (11, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/9b12d4ce1f5d474fb51a1ab969cea07d.png', '', 30, true, '2026-09-27 14:27:46.391060', '2026-09-27 14:29:32.906205'),
  (10, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/0564b4a0208b4dcdad2b0a788dcf1e50.png', '', 40, true, '2026-09-27 14:27:38.720166', '2026-09-27 14:27:38.720184'),
  (8, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/d2e8b18048b5437898f26790184b4ef1.png', '', 50, true, '2026-09-27 14:27:26.104466', '2026-09-27 14:29:34.191685'),
  (12, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/d4a60781967c40ee9f361d40fbf975ec.png', '', 60, true, '2026-09-27 14:27:54.641561', '2026-09-27 14:27:54.641580'),
  (13, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/ad791a6cd9fc45dc8bd54e2b72389b00.png', '', 70, true, '2026-09-27 14:28:03.663636', '2026-09-27 14:28:03.663673'),
  (14, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/f1f09090df4547cc93538a2555792bd9.png', '', 80, true, '2026-09-27 14:28:20.861417', '2026-09-27 14:28:20.861490'),
  (15, '', '', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/5fd9d6215ae84b24ae61b282d135c094.png', '', 90, true, '2026-09-27 14:28:49.056086', '2026-09-27 14:28:49.056121')
on conflict (id) do update set name = excluded.name, role = excluded.role, image_url = excluded.image_url, link_url = excluded.link_url, "order" = excluded."order", is_active = excluded.is_active, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.coaches (id, initials, name, qualification, focus, image_url, "order", is_active, created_at, updated_at) values
  (1, 'A', 'Adeyomi', 'MSc Strategic Project Management · MSc Urban Planning', 'PMP preparation, scheduling and professional evidence.', '', 10, true, '2026-09-07 08:00:53.763491', '2026-09-08 08:42:22.193364'),
  (2, 'P', 'Patryck', 'MSc Strategic Project Management', 'Project management thinking, evidence development and study progress.', '', 20, true, '2026-09-07 08:00:53.769716', '2026-09-08 08:42:22.199468'),
  (3, 'A', 'Aryan', 'MSc Strategic Project Management', 'Portfolio evidence, study planning and workplace application.', '', 30, true, '2026-09-07 08:00:53.775734', '2026-09-08 08:42:22.205374'),
  (4, 'DR', 'Dr Randa', 'MSc · PhD in Operations Research', 'Analytical thinking, data-informed decisions and structured evidence.', '', 40, true, '2026-09-07 08:00:53.781681', '2026-09-08 08:42:22.211316')
on conflict (id) do update set initials = excluded.initials, name = excluded.name, qualification = excluded.qualification, focus = excluded.focus, image_url = excluded.image_url, "order" = excluded."order", is_active = excluded.is_active, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.mentors (id, initials, name, role_title, affiliation, specialties, biography, image_url, linkedin_url, "order", is_active, created_at, updated_at) values
  (1, 'SJ', 'Dr. Stephen Jenner', 'Managing Portfolio Specialist', 'UK Senior Civil Service', ARRAY['Portfolio Management', 'Benefits Management', 'Public Sector']::text[], 'Extensive experience at senior level of the UK Senior Civil Service, where he was Director of Criminal Justice IT and benefits management adviser on a range of cross-government programmes.', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/3e4cdca05f8e4738a8a77cd84a2c3324.jpg', 'https://www.linkedin.com/', 10, true, '2026-08-31 08:53:24.515423', '2026-09-17 08:31:39.202236'),
  (2, 'RM', 'Dr. Ray Mead', 'Project Management Consultant', 'Founding Partner, p3m global', ARRAY['Project Management', 'Strategic Execution', 'P3M']::text[], 'Founding Partner at p3m global, a leading consultancy in delivering sustainable change and strategic execution. With over 20 years in the P3M industry, he is a recognised thought leader advising FTSE 100 boards.', 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/47e016d8301c48a5a435f9bd6d77770d.jpg', 'https://www.linkedin.com/', 20, true, '2026-08-31 08:53:24.518076', '2026-09-17 08:32:01.138987'),
  (3, 'AB', 'Dr. Amgad Badewi', 'Project Management Specialist', 'Reader, University of Kent', ARRAY['Project Management', 'Programme Management']::text[], 'A highly accomplished academic and practitioner in Project and Programme Management, with a PhD from Cranfield University, serving as Reader at the University of Kent and holding multiple leadership roles.', '/assets/media/mentors/2026/09/Dr._Amgad_Badew.jpg', 'https://www.linkedin.com/', 30, true, '2026-08-31 08:53:24.518975', '2026-09-08 08:42:22.186976')
on conflict (id) do update set initials = excluded.initials, name = excluded.name, role_title = excluded.role_title, affiliation = excluded.affiliation, specialties = excluded.specialties, biography = excluded.biography, image_url = excluded.image_url, linkedin_url = excluded.linkedin_url, "order" = excluded."order", is_active = excluded.is_active, created_at = excluded.created_at, updated_at = excluded.updated_at;

insert into public.short_courses (id, slug, title, category, duration, format, owner, audience, summary, focus, detail, icon, image_url, "order", is_active, created_at, updated_at) values
  (1, 'ai-in-project-controls', 'AI in Project Controls & Management', 'AI & Digital Delivery', '4 months', 'Professional learning', 'Institute of Project Controls', 'Project managers, planners and PMO teams seeking practical, supervised uses of AI.', 'Use AI-enabled tools to support project information, reporting, dashboards and decisions while keeping professional judgement in control.', '["Responsible AI use","Project data and dashboards","Decision support","Assurance and judgement"]'::jsonb, '{"positioning":"A practical course for professionals who want to use AI responsibly in project controls, reporting and decision support without replacing professional judgement.","bestFor":["Project controls professionals who work with schedule, cost, risk or performance data.","PMO teams exploring AI-assisted reporting, dashboards and workflow support.","Project managers who need a governed way to test AI tools on real project information."],"learningBlocks":[{"title":"Responsible AI use","body":"Understand where AI can support project work, where it should not be trusted blindly and how to keep human approval in the loop."},{"title":"Project data readiness","body":"Review the quality, structure and limitations of schedule, cost, risk and progress data before using AI-enabled tools."},{"title":"Dashboards and reporting","body":"Explore prompts, workflows and review methods that turn project information into clearer dashboards, summaries and decision packs."},{"title":"Governance and assurance","body":"Create guardrails for confidentiality, traceability, review, escalation and accountable use of AI outputs."}],"workplaceOutputs":["AI use-case register","Prompt and review checklist","Project dashboard concept","Human-in-the-loop approval workflow","AI risk and governance note"],"professionalContext":"PMI''s 2026 PMP update highlights AI in project-based scenarios. This course treats AI as supervised professional support, not as a replacement for project controls expertise."}'::jsonb, 'ri-robot-2-line', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1800&q=80', 10, true, '2026-09-21 12:13:53.191296', '2026-09-21 12:13:53.191348'),
  (2, 'project-planning-control', 'Project Planning & Control', 'Planning & Controls', '4 months', 'Professional learning', 'APMG International', 'Planners, project managers and controls professionals building integrated planning skills.', 'Connect scope, schedule, cost and performance into one practical control picture.', '["Integrated planning","Schedule and cost links","Performance measurement","Control decisions"]'::jsonb, '{"positioning":"A controls-focused course for building the discipline to connect scope, schedule, cost, risk and progress into one credible delivery baseline.","bestFor":["Planners, schedulers and project controls analysts developing integrated planning capability.","Project managers who need a stronger grip on baselines, dependencies and progress evidence.","Teams that need common planning language across delivery, cost and reporting."],"learningBlocks":[{"title":"Planning foundations","body":"Structure scope, deliverables, assumptions, dependencies and milestones before building the schedule."},{"title":"Schedule and cost links","body":"Connect time, resource and cost information so that progress reporting supports real control decisions."},{"title":"Monitoring and control","body":"Use progress evidence, variance, forecast confidence and exception reporting to keep plans alive."},{"title":"Change and governance","body":"Apply change-control discipline so that baseline movement is understood, approved and traceable."}],"workplaceOutputs":["Integrated baseline","Milestone and dependency map","Progress reporting pack","Change-control log","Schedule health review"],"professionalContext":"The APM Project Planning & Control qualification is linked to practical guidance on planning, scheduling, monitoring and control across time, cost and risk."}'::jsonb, 'ri-calendar-check-line', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1800&q=80', 20, true, '2026-09-21 12:13:53.197720', '2026-09-21 12:13:53.197747'),
  (3, 'earned-value-management', 'Earned Value Management', 'Cost & Performance', '4 months', 'Professional learning', 'APMG International', 'Cost engineers, project controllers and managers who need a reliable view of performance.', 'Develop earned value practice that combines scope, schedule and cost to support forecasting and control.', '["EVM foundations","Variance analysis","Forecasting","Performance reporting"]'::jsonb, '{"positioning":"A performance-measurement course for professionals who need to interpret cost and schedule performance with more confidence than simple spend tracking allows.","bestFor":["Cost engineers and project controllers responsible for performance analysis.","Project managers who need better forecasting and variance interpretation.","Organisations building transparent performance measurement baselines."],"learningBlocks":[{"title":"Performance measurement baseline","body":"Understand how scope, schedule and budget form the reference point for meaningful performance measurement."},{"title":"Core EVM measures","body":"Work with earned value, planned value, actual cost, variance, indices and forecast indicators."},{"title":"Data integrity","body":"Assess whether progress measurement, cost capture and coding structures are reliable enough for EVM."},{"title":"Forecast interpretation","body":"Translate EVM results into delivery conversations about confidence, corrective action and governance."}],"workplaceOutputs":["EVM baseline map","Variance analysis note","Forecast dashboard","Data-quality checklist","Performance narrative for leaders"],"professionalContext":"APM describes Earned Value Management as integrating scope, time and cost objectives and establishing a baseline for performance measurement."}'::jsonb, 'ri-line-chart-line', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1800&q=80', 30, true, '2026-09-21 12:13:53.200628', '2026-09-21 12:13:53.200718'),
  (4, 'pmi-scheduling-professional', 'PMI Scheduling Professional Preparation', 'Scheduling', '4 months', 'Professional learning', 'Project Management Institute', 'Planners, schedulers and project controls professionals developing specialist scheduling capability.', 'Build specialist scheduling capability and prepare for the PMI-SP route through applied practice.', '["Schedule development","Critical path analysis","Schedule control","Exam preparation"]'::jsonb, '{"positioning":"A specialist scheduling course for professionals who create, maintain, analyse and communicate project schedules in complex delivery environments.","bestFor":["Planners and schedulers preparing for a more specialist scheduling role.","Project controls teams managing complex dependencies, resources and timelines.","Professionals considering the PMI-SP certification pathway."],"learningBlocks":[{"title":"Schedule strategy","body":"Define the scheduling approach, governance rhythm, assumptions and stakeholder needs before detail planning begins."},{"title":"Schedule development","body":"Build logic-led schedules with activities, dependencies, constraints, milestones and appropriate levels of detail."},{"title":"Monitoring and control","body":"Update, analyse and report schedule movement, critical path pressure and delivery confidence."},{"title":"Schedule communication","body":"Translate schedule analysis into clear messages for project teams, sponsors and decision forums."}],"workplaceOutputs":["Schedule strategy note","Logic and dependency review","Critical path analysis","Schedule update protocol","Stakeholder schedule report"],"professionalContext":"PMI-SP is a PMI specialist certification focused on project scheduling, with exam domains covering schedule strategy, development, monitoring and stakeholder communications."}'::jsonb, 'ri-calendar-2-line', 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1800&q=80', 40, true, '2026-09-21 12:13:53.203833', '2026-09-21 12:13:53.203879'),
  (5, 'apm-risk-management', 'APM Risk Management Level 1 & Applied Practice', 'Risk', '4 months', 'Professional learning', 'Association for Project Management', 'Professionals who need a structured approach to project uncertainty.', 'Build an applied approach to identifying, analysing and responding to uncertainty across the project lifecycle.', '["Risk identification","Risk analysis","Response planning","Workplace application"]'::jsonb, '{"positioning":"A risk course for building structured risk thinking that can be used in live projects, controls reviews and delivery decision-making.","bestFor":["Project professionals who contribute to risk management but need a clearer framework.","Controls, PMO and assurance teams who maintain risk registers and escalation routes.","Learners preparing for APM Project Risk Management Level 1 knowledge."],"learningBlocks":[{"title":"Risk foundations","body":"Clarify the difference between uncertainty, risk, issue, assumption and opportunity."},{"title":"Identification and ownership","body":"Develop practical approaches for capturing risks, causes, effects, owners and triggers."},{"title":"Assessment and response","body":"Use qualitative assessment and response planning to support proportionate action."},{"title":"Review and escalation","body":"Keep risk information active through review rhythm, controls evidence and decision escalation."}],"workplaceOutputs":["Improved risk register","Risk scoring guide","Response plan","Escalation criteria","Risk review pack"],"professionalContext":"APM states that its Level 1 Project Risk Management certificate tests foundation knowledge sufficient to contribute to risk management within a project."}'::jsonb, 'ri-alert-line', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1800&q=80', 50, true, '2026-09-21 12:13:53.205751', '2026-09-21 12:13:53.205777'),
  (6, 'managing-portfolios', 'Managing Portfolios', 'Portfolio & Governance', '4 months', 'Professional learning', 'APMG International', 'Portfolio, PMO and change leaders prioritising investment and delivery capacity.', 'Develop the judgement to prioritise investment, balance delivery capacity and govern a portfolio against strategy.', '["Strategic alignment","Prioritisation","Capacity decisions","Portfolio governance"]'::jsonb, '{"positioning":"A portfolio course for professionals who need to connect investment choices, delivery capacity and governance with strategic contribution.","bestFor":["Portfolio managers, PMO leaders and governance teams supporting investment decisions.","Senior managers who need clearer prioritisation and resource trade-off conversations.","Project and programme leaders who want to understand portfolio context."],"learningBlocks":[{"title":"Portfolio purpose","body":"Define how a portfolio contributes to strategy, value and organisational decision-making."},{"title":"Prioritisation","body":"Compare initiatives using contribution, risk, affordability, dependency and capacity considerations."},{"title":"Benefits and value","body":"Connect portfolio choices to measurable benefits, outcomes and strategic impact."},{"title":"Governance rhythm","body":"Create practical portfolio forums, dashboards and escalation paths that support action."}],"workplaceOutputs":["Portfolio prioritisation model","Investment decision pack","Benefits map","Capacity view","Portfolio governance cadence"],"professionalContext":"APMG describes Managing Portfolios as focusing on strategic contribution, prioritising the right projects and balancing available resources."}'::jsonb, 'ri-briefcase-4-line', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=80', 60, true, '2026-09-21 12:13:53.207486', '2026-09-21 12:13:53.207509'),
  (7, 'managing-successful-programmes', 'Managing Successful Programmes', 'Programme Management', '4 months', 'Professional learning', 'PeopleCert / AXELOS', 'Programme managers and change professionals coordinating multiple projects.', 'Explore how programmes coordinate projects and change activity towards agreed organisational outcomes.', '["Programme governance","Benefits management","Stakeholder leadership","Change coordination"]'::jsonb, '{"positioning":"A programme-management course for professionals coordinating multiple projects and change activity towards defined outcomes and benefits.","bestFor":["Programme managers and project leaders moving into programme environments.","PMO professionals supporting programme governance, benefits and dependency management.","Business-change teams working across complex initiatives."],"learningBlocks":[{"title":"Programme structure","body":"Understand how programmes organise related projects, change activity, governance and outcomes."},{"title":"Benefits realisation","body":"Connect programme activity to benefits, transition states and stakeholder value."},{"title":"Risk and dependency","body":"Coordinate cross-project dependencies, risks, issues and decision points."},{"title":"Stakeholder engagement","body":"Plan communication, involvement and change leadership across a programme lifecycle."}],"workplaceOutputs":["Programme blueprint","Benefits profile","Dependency map","Programme risk log","Stakeholder engagement plan"],"professionalContext":"PeopleCert describes MSP as a framework for managing complex initiatives, aligning programmes to business objectives and focusing on benefits and stakeholder engagement."}'::jsonb, 'ri-node-tree', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1800&q=80', 70, true, '2026-09-21 12:13:53.209559', '2026-09-21 12:13:53.209610'),
  (8, 'pmp', 'Project Management Professional Preparation', 'Professional Certification', '8 months', 'Professional learning', 'Project Management Institute', 'Project managers and delivery professionals seeking the PMP credential.', 'Build structured project management knowledge through practical discussion, applied examples and focused revision.', '["PMP knowledge areas","Applied examples","Revision discipline","Professional discussion"]'::jsonb, '{"positioning":"A PMP preparation course that connects exam readiness with the leadership, technical and business judgement needed in real project environments.","bestFor":["Project managers preparing for the PMP certification route.","Delivery professionals who need broader project management structure and language.","Professionals who want to strengthen leadership, delivery process and business-impact thinking."],"learningBlocks":[{"title":"People and leadership","body":"Develop team leadership, stakeholder engagement, conflict handling and communication judgement."},{"title":"Process discipline","body":"Review planning, delivery, risk, quality, procurement, scope, schedule and change control."},{"title":"Business environment","body":"Connect project decisions to value, compliance, organisational change and strategic outcomes."},{"title":"Exam preparation","body":"Use structured revision, practice questions and scenario discussion to prepare with confidence."}],"workplaceOutputs":["PMP study plan","Scenario decision log","Stakeholder strategy","Integrated delivery checklist","Exam-readiness review"],"professionalContext":"PMI''s 2026 PMP update places more emphasis on outcomes, value, business impact, AI, sustainability and stakeholder engagement."}'::jsonb, 'ri-award-line', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1800&q=80', 80, true, '2026-09-21 12:13:53.213688', '2026-09-21 12:13:53.213715'),
  (9, 'chartered-project-professional', 'APM Chartered Project Professional Development', 'Professional Certification', '4 months', 'Professional learning', 'Association for Project Management', 'Experienced project professionals preparing evidence of technical knowledge and professional practice.', 'Prepare evidence for the APM Chartered Project Professional route, subject to APM requirements.', '["Technical knowledge evidence","Professional practice","Submission structure","Reflective judgement"]'::jsonb, '{"positioning":"A professional-evidence course for experienced practitioners who need to organise technical knowledge, professional practice and reflective development.","bestFor":["Experienced project professionals considering the APM ChPP route.","Practitioners who need help selecting suitable project examples and evidence.","Professionals building stronger reflective practice and CPD discipline."],"learningBlocks":[{"title":"Readiness and route selection","body":"Review professional activity, CPD position, experience and possible evidence routes."},{"title":"Project example selection","body":"Identify sufficiently strong project examples and describe your role clearly."},{"title":"Competence evidence","body":"Structure concise evidence statements that connect action, judgement, context and result."},{"title":"Professional reflection","body":"Develop CPD, ethical practice and reflection habits that support ongoing professional development."}],"workplaceOutputs":["ChPP readiness map","Project example shortlist","Competence evidence draft","CPD development plan","Professional reflection log"],"professionalContext":"APM guidance highlights CPD, professional conduct, project examples and written competence evidence as important parts of ChPP preparation. APM independently assesses and awards ChPP."}'::jsonb, 'ri-shield-star-line', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1800&q=80', 90, true, '2026-09-21 12:13:53.216843', '2026-09-21 12:13:53.216867'),
  (10, 'pmi-pmo-certified-professional', 'PMI PMO Certified Professional Preparation', 'PMO & Governance', '4 months', 'Professional learning', 'Project Management Institute', 'PMO practitioners and leaders developing a value-focused PMO.', 'Develop a value-focused PMO approach through practical and applied learning.', '["PMO value","Operating models","Governance services","Exam preparation"]'::jsonb, '{"positioning":"A PMO certification-preparation course focused on value-led PMO design, operation, alignment and continuous improvement.","bestFor":["PMO leaders and team members who want to demonstrate specialist PMO capability.","Project managers moving into PMO, portfolio or governance roles.","Organisations that need PMO services to support measurable value rather than reporting alone."],"learningBlocks":[{"title":"PMO strategic alignment","body":"Connect PMO purpose, services and success measures to organisational needs."},{"title":"PMO design","body":"Explore operating models, service catalogues, roles, governance interfaces and maturity considerations."},{"title":"PMO operation","body":"Develop approaches for reporting, standards, assurance, portfolio support and performance rhythm."},{"title":"PMO improvement","body":"Use feedback, maturity evidence and value measures to strengthen PMO credibility over time."}],"workplaceOutputs":["PMO service catalogue","Operating model map","PMO value measures","Governance calendar","Improvement backlog"],"professionalContext":"PMI-PMOCP focuses on leading and shaping PMOs, with exam domains covering PMO strategy, design, operation, improvement and people."}'::jsonb, 'ri-building-4-line', 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1800&q=80', 100, true, '2026-09-21 12:13:53.221667', '2026-09-21 12:13:53.221703'),
  (11, 'pmo-level-6', 'Certified PMO Professional Level 6', 'PMO & Governance', '16 months', 'Professional learning', 'Institute of Project Controls', 'PMO professionals, project leaders and managers developing strategic PMO capability.', 'Develop strategic PMO capability across planning, risk, quality, stakeholder engagement and reporting systems.', '["Project planning and control","Risk and quality","Stakeholder engagement","PMO reporting systems"]'::jsonb, '{"positioning":"A broader PMO development route for professionals building governance, reporting, stakeholder, controls and assurance capability at a more strategic level.","bestFor":["PMO professionals developing from reporting support into trusted decision support.","Project controls and governance practitioners working across complex portfolios.","Managers who need stronger PMO capability without treating the PMO as admin only."],"learningBlocks":[{"title":"PMO governance","body":"Design governance rhythms, decision forums, controls standards and escalation routes."},{"title":"Integrated controls","body":"Bring schedule, cost, risk, quality, change and benefits information into a coherent PMO view."},{"title":"Stakeholder leadership","body":"Build the communication and advisory capability needed for senior stakeholder confidence."},{"title":"Evidence and assurance","body":"Create reliable evidence packs, assurance reviews and improvement actions that leaders can use."}],"workplaceOutputs":["PMO operating model","Integrated controls dashboard","Assurance review pack","Stakeholder reporting framework","Capability improvement plan"],"professionalContext":"This course is positioned as College professional development for PMO capability. External professional recognition remains subject to the requirements of the relevant awarding or professional body."}'::jsonb, 'ri-stack-line', 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1800&q=80', 110, true, '2026-09-21 12:13:53.223290', '2026-09-21 12:13:53.223313')
on conflict (id) do update set slug = excluded.slug, title = excluded.title, category = excluded.category, duration = excluded.duration, format = excluded.format, owner = excluded.owner, audience = excluded.audience, summary = excluded.summary, focus = excluded.focus, detail = excluded.detail, icon = excluded.icon, image_url = excluded.image_url, "order" = excluded."order", is_active = excluded.is_active, created_at = excluded.created_at, updated_at = excluded.updated_at;

select setval(pg_get_serial_sequence('public.ipc_images', 'id'), coalesce((select max(id) from public.ipc_images), 1), true);
select setval(pg_get_serial_sequence('public.partners', 'id'), coalesce((select max(id) from public.partners), 1), true);
select setval(pg_get_serial_sequence('public.sectors', 'id'), coalesce((select max(id) from public.sectors), 1), true);
select setval(pg_get_serial_sequence('public.professional_credentials', 'id'), coalesce((select max(id) from public.professional_credentials), 1), true);
select setval(pg_get_serial_sequence('public.coaches', 'id'), coalesce((select max(id) from public.coaches), 1), true);
select setval(pg_get_serial_sequence('public.mentors', 'id'), coalesce((select max(id) from public.mentors), 1), true);
select setval(pg_get_serial_sequence('public.short_courses', 'id'), coalesce((select max(id) from public.short_courses), 1), true);

commit;
