-- Supabase dashboard admin policies.
-- Run after SUPABASE_PUBLIC_CONTENT_SCHEMA.sql.
--
-- 1) Replace the placeholder email below with your dashboard login email.
-- 2) Run this file in the Supabase SQL editor.
-- 3) Create the same user in Supabase Authentication with a password.

create table if not exists public.dashboard_admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.dashboard_admin_users (email, is_active)
values ('REPLACE_WITH_YOUR_ADMIN_EMAIL@example.com', true)
on conflict (email) do update set is_active = excluded.is_active;

create or replace function public.is_dashboard_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
      from public.dashboard_admin_users admin
     where lower(admin.email) = lower(coalesce(auth.jwt() #>> '{email}', ''))
       and admin.is_active = true
  );
$$;

alter table public.dashboard_admin_users enable row level security;

drop policy if exists "Dashboard admins read own admin status" on public.dashboard_admin_users;
create policy "Dashboard admins read own admin status"
  on public.dashboard_admin_users
  for select
  to authenticated
  using (lower(email) = lower(coalesce(auth.jwt() #>> '{email}', '')) and is_active = true);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'ipc_images',
    'partners',
    'sectors',
    'professional_credentials',
    'coaches',
    'mentors',
    'short_courses',
    'articles',
    'case_studies',
    'testimonials',
    'event_categories',
    'events',
    'event_classifications',
    'enquiries'
  ]
  loop
    execute format('drop policy if exists "Dashboard admins manage %1$s" on public.%1$I', table_name);
    execute format(
      'create policy "Dashboard admins manage %1$s" on public.%1$I for all to authenticated using (public.is_dashboard_admin()) with check (public.is_dashboard_admin())',
      table_name
    );
  end loop;
end $$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'images',
  'images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']::text[]
)
on conflict (id) do update
set public = true,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read images bucket" on storage.objects;
create policy "Public read images bucket"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'images');

drop policy if exists "Dashboard admins upload images" on storage.objects;
create policy "Dashboard admins upload images"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'images' and public.is_dashboard_admin());

drop policy if exists "Dashboard admins update images" on storage.objects;
create policy "Dashboard admins update images"
  on storage.objects
  for update
  to authenticated
  using (bucket_id = 'images' and public.is_dashboard_admin())
  with check (bucket_id = 'images' and public.is_dashboard_admin());

drop policy if exists "Dashboard admins delete images" on storage.objects;
create policy "Dashboard admins delete images"
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'images' and public.is_dashboard_admin());
