-- Testimonial programme dropdown management.
-- Run this once in Supabase SQL editor.
-- It creates the dashboard-managed programme list used by the public review form.
-- Safe to run more than once. Existing rows are updated, not deleted.

create table if not exists public.testimonial_programmes (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists testimonial_programmes_public_order_idx
  on public.testimonial_programmes (is_active, "order", name, id);

alter table public.testimonial_programmes enable row level security;

drop policy if exists "Public read active testimonial programmes" on public.testimonial_programmes;
create policy "Public read active testimonial programmes"
  on public.testimonial_programmes
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Dashboard admins manage testimonial_programmes" on public.testimonial_programmes;
create policy "Dashboard admins manage testimonial_programmes"
  on public.testimonial_programmes
  for all
  to authenticated
  using (public.is_dashboard_admin())
  with check (public.is_dashboard_admin());

insert into public.testimonial_programmes (slug, name, "order", is_active)
values
  ('associate-project-manager-level-4', 'Associate Project Manager Level 4', 10, true),
  ('pcp-level-6', 'Project Controls Professional Level 6', 20, true),
  ('operational-pcp', 'Project Controls Professional Level 6 - Operational Pathway', 30, true),
  ('strategic-pcp', 'Project Controls Professional Level 6 - Strategic Pathway', 40, true),
  ('strategic-operational-pcp', 'Project Controls Professional Level 6 - Strategic + Operational Pathway', 50, true),
  ('chartered-pmo-pathway', 'Project Controls Professional Level 6 - Chartered PMO Pathway', 60, true),
  ('pmo-pcp', 'Certified PMO Professional Level 6', 70, true),
  ('engineering', 'Engineering & Manufacturing Project Controls Route', 80, true),
  ('public-sector', 'Public Sector Project Controls Route', 90, true),
  ('energy', 'Energy & Utilities Project Controls Route', 100, true),
  ('commercial', 'Commercial Project Controls Route', 110, true),
  ('ipc', 'Institute of Project Controls', 120, true)
on conflict (slug) do update
set name = excluded.name,
    "order" = excluded."order",
    updated_at = now();

notify pgrst, 'reload schema';
