-- Supabase public-content schema, phase 1.
-- Applies the first frontend migration batch:
-- ipc_images, partners, sectors.
--
-- Run this in the Supabase SQL editor after reviewing names and policies.
-- Public visitors can read active rows only. Writes stay blocked for anon users.

create table if not exists public.ipc_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  alt_text text not null default '',
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null default '',
  link_url text not null default '',
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sectors (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null default '',
  icon text not null default '',
  image_url text not null default '',
  link_url text not null default '',
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ipc_images_public_order_idx on public.ipc_images (is_active, "order", id);
create index if not exists partners_public_order_idx on public.partners (is_active, "order", id);
create index if not exists sectors_public_order_idx on public.sectors (is_active, "order", id);
create index if not exists sectors_public_slug_idx on public.sectors (slug) where is_active = true;

alter table public.ipc_images enable row level security;
alter table public.partners enable row level security;
alter table public.sectors enable row level security;

drop policy if exists "Public read active IPC images" on public.ipc_images;
create policy "Public read active IPC images"
  on public.ipc_images
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Public read active partners" on public.partners;
create policy "Public read active partners"
  on public.partners
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Public read active sectors" on public.sectors;
create policy "Public read active sectors"
  on public.sectors
  for select
  to anon, authenticated
  using (is_active = true);

create table if not exists public.professional_credentials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default '',
  image_url text not null default '',
  link_url text not null default '',
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coaches (
  id bigint generated by default as identity primary key,
  initials text not null default '',
  name text not null,
  qualification text not null default '',
  focus text not null default '',
  image_url text not null default '',
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mentors (
  id bigint generated by default as identity primary key,
  initials text not null default '',
  name text not null,
  role_title text not null default '',
  affiliation text not null default '',
  specialties text[] not null default '{}',
  biography text not null default '',
  image_url text not null default '',
  linkedin_url text not null default '',
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists professional_credentials_public_order_idx on public.professional_credentials (is_active, "order", id);
create index if not exists coaches_public_order_idx on public.coaches (is_active, "order", id);
create index if not exists mentors_public_order_idx on public.mentors (is_active, "order", id);

alter table public.professional_credentials enable row level security;
alter table public.coaches enable row level security;
alter table public.mentors enable row level security;

drop policy if exists "Public read active professional credentials" on public.professional_credentials;
create policy "Public read active professional credentials"
  on public.professional_credentials
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Public read active coaches" on public.coaches;
create policy "Public read active coaches"
  on public.coaches
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Public read active mentors" on public.mentors;
create policy "Public read active mentors"
  on public.mentors
  for select
  to anon, authenticated
  using (is_active = true);

create table if not exists public.short_courses (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null default '',
  duration text not null default '',
  format text not null default 'Professional learning',
  owner text not null default '',
  audience text not null default '',
  summary text not null default '',
  focus jsonb not null default '[]'::jsonb,
  detail jsonb not null default '{}'::jsonb,
  icon text not null default 'ri-book-open-line',
  image_url text not null default '',
  "order" integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists short_courses_public_order_idx on public.short_courses (is_active, "order", title);
create index if not exists short_courses_public_slug_idx on public.short_courses (slug) where is_active = true;

alter table public.short_courses enable row level security;

drop policy if exists "Public read active short courses" on public.short_courses;
create policy "Public read active short courses"
  on public.short_courses
  for select
  to anon, authenticated
  using (is_active = true);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null default '',
  category text not null default '',
  author text not null default '',
  image_url text not null default '',
  image_alt text not null default '',
  read_minutes integer not null default 1,
  is_published boolean not null default false,
  published_at timestamptz,
  "order" integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.case_studies (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  sector text not null default '',
  client_name text not null default '',
  headline text not null default '',
  summary text not null default '',
  challenge text not null default '',
  approach text not null default '',
  outcome text not null default '',
  metrics jsonb not null default '[]'::jsonb,
  image_url text not null default '',
  image_alt text not null default '',
  is_featured boolean not null default false,
  is_published boolean not null default false,
  published_at timestamptz,
  "order" integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  programme text not null default '',
  programme_label text not null default '',
  reviewer_type text not null default 'professional',
  review text not null default '',
  photo_url text not null default '',
  consent boolean not null default false,
  status text not null default 'pending',
  is_featured boolean not null default false,
  "order" integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  kind text not null default 'local',
  remote_id text not null default '',
  is_visible boolean not null default true,
  "order" integer not null default 0
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null default '',
  source text not null default 'manual',
  source_category_id bigint references public.event_categories(id) on delete set null,
  format text not null default 'online',
  cadence text not null default '',
  summary text not null default '',
  description text not null default '',
  image_url text not null default '',
  image_alt text not null default '',
  starts_at timestamptz,
  ends_at timestamptz,
  timezone text not null default 'Europe/London',
  location text not null default '',
  organizer text not null default '',
  remote_status text not null default 'live',
  sales_status text not null default '',
  price_label text not null default '',
  is_featured boolean not null default false,
  highlights_url text not null default '',
  cta_label text not null default 'Register',
  cta_href text not null default '',
  source_url text not null default '',
  last_synced_at timestamptz,
  source_is_public boolean not null default true,
  is_active boolean not null default true,
  "order" integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_classifications (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  eventcategory_id bigint not null references public.event_categories(id) on delete cascade,
  unique (event_id, eventcategory_id)
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null default '',
  organisation text not null default '',
  role_title text not null default '',
  enquiry_type text not null default 'Website enquiry',
  message text not null default '',
  source_path text not null default '',
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists articles_public_order_idx on public.articles (is_published, "order", published_at desc, id);
create index if not exists articles_public_slug_idx on public.articles (slug) where is_published = true;
create index if not exists case_studies_public_order_idx on public.case_studies (is_published, "order", published_at desc, id);
create index if not exists case_studies_public_slug_idx on public.case_studies (slug) where is_published = true;
create index if not exists testimonials_public_order_idx on public.testimonials (status, is_featured, "order", id);
create index if not exists event_categories_public_order_idx on public.event_categories (is_visible, "order", name);
create index if not exists events_public_order_idx on public.events (is_active, is_featured, "order", starts_at, id);
create index if not exists events_public_slug_idx on public.events (slug) where is_active = true;
create index if not exists event_classifications_event_idx on public.event_classifications (event_id);
create index if not exists event_classifications_category_idx on public.event_classifications (eventcategory_id);
create index if not exists enquiries_created_idx on public.enquiries (created_at desc);

alter table public.articles enable row level security;
alter table public.case_studies enable row level security;
alter table public.testimonials enable row level security;
alter table public.event_categories enable row level security;
alter table public.events enable row level security;
alter table public.event_classifications enable row level security;
alter table public.enquiries enable row level security;

drop policy if exists "Public read published articles" on public.articles;
create policy "Public read published articles"
  on public.articles
  for select
  to anon, authenticated
  using (is_published = true and published_at is not null and published_at <= now());

drop policy if exists "Public read published case studies" on public.case_studies;
create policy "Public read published case studies"
  on public.case_studies
  for select
  to anon, authenticated
  using (is_published = true and published_at is not null and published_at <= now());

drop policy if exists "Public read approved testimonials" on public.testimonials;
create policy "Public read approved testimonials"
  on public.testimonials
  for select
  to anon, authenticated
  using (status = 'approved' and consent = true);

drop policy if exists "Public read visible event categories" on public.event_categories;
create policy "Public read visible event categories"
  on public.event_categories
  for select
  to anon, authenticated
  using (is_visible = true);

drop policy if exists "Public read active events" on public.events;
create policy "Public read active events"
  on public.events
  for select
  to anon, authenticated
  using (
    is_active = true
    and remote_status not in ('deleted', 'private', 'unpublished', 'missing')
    and (
      (source_is_public = true and remote_status <> 'draft')
      or (
        source = 'eventbrite'
        and remote_status = 'draft'
        and coalesce(ends_at, starts_at) > now()
      )
    )
  );

drop policy if exists "Public read event classifications" on public.event_classifications;
create policy "Public read event classifications"
  on public.event_classifications
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public submit enquiries" on public.enquiries;
create policy "Public submit enquiries"
  on public.enquiries
  for insert
  to anon, authenticated
  with check (
    length(trim(name)) > 0
    and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
    and status = 'new'
  );
