import { useState } from 'react';
import { cmsApi } from '../api/client';
import type { EventCategory } from '@/services/eventsApi';
export default function EventCategories({ categories, reload }: { categories: EventCategory[]; reload: () => Promise<void> }) {
  const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [kind, setKind] = useState('local'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const act = async (work: () => Promise<unknown>) => { setBusy(true); setError(''); try { await work(); await reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save this classification. Check the details and try again.'); } finally { setBusy(false); } };
  return <div><h2 className="text-xl font-bold">Categories & visibility</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-foreground-600">Hiding a category or classification hides every linked event across the whole public site, including its direct URL. If an event has several classifications, any hidden classification takes priority. Sync never resets these choices.</p>{error && <p role="alert" className="mt-4 text-red-700">{error}</p>}
    <form onSubmit={e => { e.preventDefault(); act(async () => { await cmsApi.post('/event-categories/', { name, slug, kind }); setName(''); setSlug(''); }); }} className="mt-6 grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-4"><label className="text-sm">Name<input required value={name} onChange={e => { setName(e.target.value); setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); }} className="mt-2 w-full rounded border p-3" /></label><label className="text-sm">Slug<input required pattern="[a-z0-9_-]+" value={slug} onChange={e => setSlug(e.target.value)} className="mt-2 w-full rounded border p-3" /></label><label className="text-sm">Type<select value={kind} onChange={e => setKind(e.target.value)} className="mt-2 w-full rounded border bg-white p-3"><option value="local">Local topic</option><option value="programme">Programme</option></select></label><button disabled={busy} className="btn-primary self-end px-4 py-3 disabled:opacity-40">Add classification</button></form>
    <div className="mt-6 space-y-3">{categories.map(category => <div key={category.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border bg-white p-5"><div><strong>{category.name}</strong><p className="mt-1 text-xs text-foreground-500">{category.kind} · {category.slug}</p></div><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" disabled={busy} checked={category.is_visible} onChange={e => act(() => cmsApi.patch(`/event-categories/${category.id}/`, { is_visible: e.target.checked }))} />{category.is_visible ? 'Visible' : 'Hidden'}</label></div>)}</div>
  </div>;
}
